AWSTemplateFormatVersion: 2010-09-09
Description: |
  Infrastructure needed for an automated backup tool.
Parameters:
  NameForBucket:
    Description: Name for the S3 backup bucket
    Type: String
    Default: 4240-backup-bucket-for-vm-presentation-f21
Resources:
  BackupGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Cloud-Backup-Group
  BackupUser:
    Type: AWS::IAM::User
    Properties:
      UserName: BackupUser
      Path: /
      Groups:
        - !Ref BackupGroup
  BackupPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: BackupPolicy
      Users:
        - !Ref BackupUser
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:Put*'
              - 's3:List*'
            Resource:
              - !Sub arn:aws:s3:::${NameForBucket}/*
              - !Sub arn:aws:s3:::${NameForBucket}
  BackupBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private
      BucketName: !Ref NameForBucket
      VersioningConfiguration:
        Status: Enabled
Outputs:
  BackupBucket:
    Description: The S3 backup bucket
    Value: !Ref BackupBucket
